sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t halderripan/complex-fibonacci-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true halderripan/complex-fibonacci-react-test npm test

after_success:
  - docker build -t halderripan/complex-fibonacci-client ./client
  - docker build -t halderripan/complex-fibonacci-nginx ./nginx
  - docker build -t halderripan/complex-fibonacci-server ./server
  - docker build -t halderripan/complex-fibonacci-worker ./worker
  # Docker Login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to docker hub
  - docker push halderripan/complex-fibonacci-client
  - docker push halderripan/complex-fibonacci-nginx
  - docker push halderripan/complex-fibonacci-server
  - docker push halderripan/complex-fibonacci-worker